### ISSUE TITLE
The size of the video section is not well aligned.

### ISSUE THREAD

**Issue by RaminMammadzada** [nrqrmz/nytimes#7]
The size of the video in the middle are of the page is not as same as the video on the original page.

- _The screenshot from your page:_

![image](https://user-images.githubusercontent.com/4702114/86255574-ee564400-bbbf-11ea-907a-3727afd01336.png)

- _Reference line in the codebase:_ 

https://github.com/nrqrmz/nytimes/blob/ea1888220dbc065089b2aff50ce1eae2d499c4f1/index.html#L235

**Comment by Prabhakarzx** [comment]
You can put bottom border and shadow on the navbar to separate it from the rest of the page when scrolling.
